.TH "Gomoku" 3 "Tue Oct 15 2019" "Version 024" "Gomoku" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gomoku
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gomoku\&.h>\fP
.SH "Detailed Description"
.PP 
Program main loop 
.PP
Definition at line 11 of file Gomoku\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Gomoku from the source code\&.
